make syslog smoke tests more robust
- always create an app for the test
- return exit code 2 if BeforeEach fails

[#76474472]

Signed-off-by: Trevor Ackerman <tackerman@pivotal.io>

diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 set -e -x
 
@@ -15,4 +15,16 @@ export GOPATH=$local_gopath:$GOPATH
 export PATH=$local_gopath/bin:$PATH
 
 go install -v github.com/onsi/ginkgo/ginkgo
-ginkgo -r -v -slowSpecThreshold=300 "$@"
+EXITSTATUS=0
+ginkgo -noColor -r --succinct -slowSpecThreshold=300 "$@" > >(tee out) || EXITSTATUS=$?
+
+# return special code 2 for less sensitive alarming when setup for the test fails (indicating we cannot run our test)
+if grep -F '[Fail] Loggregator: Syslog drains [BeforeEach] forwards app messages to registered syslog drains' out; then
+  exit 2
+fi
+
+if [ $EXITSTATUS -eq 0 ]; then
+ exit 0
+else
+ exit 1
+fi
